title: Jose Ramirez # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Currently a student a California State University of Sacramento studying computer science<br>
  <br>I love learning. Whether that be learning a new programming library, or how to fill out my own W2, I enjoy the process of learning.<br>
  <a href="www.linkedin.com/in/josem-jramirez">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
